# Generated by Django 6.0.1 on 2026-02-02 04:40

import apps.lists.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubtitleList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("is_hide", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.lists.models.subtitle_list_image_path,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="CSS цвет фона (например: #ffffff)",
                        max_length=20,
                    ),
                ),
                ("quantity_words", models.PositiveIntegerField(default=0)),
                ("quantity_words_frequencies", models.PositiveIntegerField(default=0)),
                ("quantity_learned_words", models.PositiveIntegerField(default=0)),
                (
                    "quantity_learned_words_frequencies",
                    models.PositiveIntegerField(default=0),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("modified_time", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_subtitle_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lists_lists",
            },
        ),
        migrations.CreateModel(
            name="SubtitleListWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.PositiveIntegerField(default=1)),
                (
                    "subtitle_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_links",
                        to="lists.subtitlelist",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitle_links",
                        to="dictionary.word",
                    ),
                ),
            ],
            options={
                "db_table": "lists_listswords",
                "unique_together": {("subtitle_list", "word")},
            },
        ),
        migrations.AddField(
            model_name="subtitlelist",
            name="words",
            field=models.ManyToManyField(
                related_name="subtitle_lists",
                through="lists.SubtitleListWord",
                to="dictionary.word",
            ),
        ),
        migrations.CreateModel(
            name="UserSubtitleList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open_menu", models.BooleanField(default=False)),
                (
                    "subtitle_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lists.subtitlelist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lists_userslists",
                "unique_together": {("user", "subtitle_list")},
            },
        ),
        migrations.AddField(
            model_name="subtitlelist",
            name="users",
            field=models.ManyToManyField(
                related_name="subtitle_lists",
                through="lists.UserSubtitleList",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
