# Generated by Django 6.0.1 on 2026-02-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtitlelist",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
