# Generated by Django 6.0.1 on 2026-02-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_usersubtitlelistprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubtitlelist",
            name="quantity_learned_words",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
