# Generated by Django 6.0.1 on 2026-02-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_usersubtitlelist_quantity_learned_words"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubtitlelist",
            name="is_open_menu",
        ),
    ]
