# Generated by Django 6.0.1 on 2026-02-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_remove_usersubtitlelist_is_open_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtitlelist",
            name="name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
