# Generated by Django 6.0.1 on 2026-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_alter_subtitlelist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtitlelistword",
            name="position",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
