# Generated by Django 6.0.1 on 2026-04-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_subtitlelistword_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlelist',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('done', 'done'), ('error', 'error')], default='processing', max_length=20),
        ),
    ]
