# Generated by Django 6.0.1 on 2026-02-03 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_rename_pathofspeech_partofspeech_and_more"),
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWordProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_learned", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                ("level_learned", models.IntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("stability_days", models.IntegerField(default=0)),
                ("is_hard", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_by_users",
                        to="dictionary.word",
                    ),
                ),
            ],
            options={
                "db_table": "study_userwordprogress",
                "unique_together": {("user", "word")},
            },
        ),
        migrations.DeleteModel(
            name="KnownWord",
        ),
    ]
