# Generated by Django 6.0.1 on 2026-02-04 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_rename_pathofspeech_partofspeech_and_more"),
        ("study", "0002_userwordprogress_delete_knownword"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userwordprogress",
            name="is_learning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="userwordprogress",
            index=models.Index(fields=["user", "word"], name="idx_uwp_user_word"),
        ),
        migrations.AddIndex(
            model_name="userwordprogress",
            index=models.Index(
                fields=["user", "is_learned", "last_reviewed_at"],
                name="idx_uwp_review_queue",
            ),
        ),
    ]
