# Generated by Django 6.0.1 on 2026-02-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_userwordprogress_is_learning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwordprogress",
            name="impressions",
            field=models.IntegerField(default=0),
        ),
    ]
