# Generated by Django 6.0.1 on 2026-02-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PathOfSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_main", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dictionary_pathofspeech",
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "transcription",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
            options={
                "db_table": "dictionary_words",
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "path_of_speech",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="dictionary.pathofspeech",
                    ),
                ),
            ],
            options={
                "db_table": "dictionary_translations",
            },
        ),
        migrations.AddField(
            model_name="pathofspeech",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts_of_speech",
                to="dictionary.word",
            ),
        ),
    ]
