# Generated by Django 6.0.1 on 2026-02-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pathofspeech",
            table="dictionary_paths_of_speech",
        ),
    ]
