# Generated by Django 6.0.1 on 2026-02-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_alter_pathofspeech_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PathOfSpeech",
            new_name="PartOfSpeech",
        ),
        migrations.RenameField(
            model_name="translation",
            old_name="path_of_speech",
            new_name="part_of_speech",
        ),
        migrations.AlterModelTable(
            name="partofspeech",
            table="dictionary_parts_of_speech",
        ),
    ]
