# Generated by Django 6.0.1 on 2026-02-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_rename_pathofspeech_partofspeech_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartOfSpeechRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "db_table": "dictionary_part_of_speech_ref",
            },
        ),
    ]
