# Generated by Django 6.0.1 on 2026-02-12 21:14

from django.db import migrations


def forwards(apps, schema_editor):
    OldPOS = apps.get_model("dictionary", "PartOfSpeech")
    NewPOS = apps.get_model("dictionary", "PartOfSpeechRef")

    unique_names = OldPOS.objects.values_list("name", flat=True).distinct()

    for name in unique_names:
        NewPOS.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_partofspeechref"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
