# Generated by Django 6.0.1 on 2026-02-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0005_auto_20260212_2114"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordPartOfSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "part_of_speech",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="word_links",
                        to="dictionary.partofspeechref",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_parts",
                        to="dictionary.word",
                    ),
                ),
            ],
            options={
                "db_table": "dictionary_word_parts",
                "unique_together": {("word", "part_of_speech")},
            },
        ),
    ]
