# Generated by Django 6.0.1 on 2026-02-12 21:25

from django.db import migrations


def forwards(apps, schema_editor):
    OldPOS = apps.get_model("dictionary", "PartOfSpeech")
    NewPOS = apps.get_model("dictionary", "PartOfSpeechRef")
    WordPart = apps.get_model("dictionary", "WordPartOfSpeech")

    for old in OldPOS.objects.iterator():
        pos_ref = NewPOS.objects.get(name=old.name)

        WordPart.objects.get_or_create(
            word=old.word,
            part_of_speech=pos_ref,
            defaults={"is_main": old.is_main},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0006_wordpartofspeech"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
