# Generated by Django 6.0.1 on 2026-02-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0007_migrate_part_of_speech_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="word_part_of_speech",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="dictionary.wordpartofspeech",
            ),
        ),
    ]
