# Generated by Django 6.0.1 on 2026-02-12 21:36

from django.db import migrations


def forwards(apps, schema_editor):
    Translation = apps.get_model("dictionary", "Translation")
    OldPOS = apps.get_model("dictionary", "PartOfSpeech")
    WordPart = apps.get_model("dictionary", "WordPartOfSpeech")
    NewPOS = apps.get_model("dictionary", "PartOfSpeechRef")

    for tr in Translation.objects.iterator():
        old_pos = tr.part_of_speech
        if not old_pos:
            continue

        pos_ref = NewPOS.objects.get(name=old_pos.name)

        word_part_of_speech = WordPart.objects.get(
            word=old_pos.word,
            part_of_speech=pos_ref,
        )

        tr.word_part_of_speech = word_part_of_speech
        tr.save(update_fields=["word_part_of_speech"])


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0008_translation_word_part_of_speech"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
