# Generated by Django 6.0.1 on 2026-02-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0009_migrate_part_translation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translation",
            name="part_of_speech",
        ),
    ]
