# Generated by Django 6.0.1 on 2026-02-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0010_remove_translation_part_of_speech"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartOfSpeech",
        ),
    ]
