# Generated by Django 6.0.1 on 2026-02-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0011_delete_partofspeech"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PartOfSpeechRef",
            new_name="PartOfSpeech",
        ),
    ]
