# Generated by Django 6.0.1 on 2026-02-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0012_rename_partofspeechref_partofspeech"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="partofspeech",
            table="dictionary_part_of_speech",
        ),
    ]
