# Generated by Django 6.0.1 on 2026-02-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0013_alter_partofspeech_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partofspeech",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="translation",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="word",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="transcription",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
